version: '3.8'

services:
  flask:

    build:
      context: ./mapnik
      dockerfile: Dockerfile
    container_name: flask_mapnik
    ports:
      - "5000:5000"
    volumes:
      - ./data:/data
      #- ./mapnik:/app
    environment:
      - FLASK_ENV=development
    
    restart: unless-stopped


volumes:
  
  data:  # Volume pour les données Mapnik